/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.pluralsight.kafka.model;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ProductType {
  TSHIRT, DESIGN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ProductType\",\"namespace\":\"com.pluralsight.kafka.model\",\"symbols\":[\"TSHIRT\",\"DESIGN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
