/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.pluralsight.kafka.model;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Color {
  GREEN, BLUE, PURPLE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Color\",\"namespace\":\"com.pluralsight.kafka.model\",\"symbols\":[\"GREEN\",\"BLUE\",\"PURPLE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
