/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.pluralsight.kafka.model;
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum DesignType {
  NONE, SUITCASE, CAR, WARNING  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"DesignType\",\"namespace\":\"com.pluralsight.kafka.model\",\"symbols\":[\"NONE\",\"SUITCASE\",\"CAR\",\"WARNING\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
